/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Prison } from "./Prison";
import { PrisonCountArgs } from "./PrisonCountArgs";
import { PrisonFindManyArgs } from "./PrisonFindManyArgs";
import { PrisonFindUniqueArgs } from "./PrisonFindUniqueArgs";
import { DeletePrisonArgs } from "./DeletePrisonArgs";
import { PrisonService } from "../prison.service";
@graphql.Resolver(() => Prison)
export class PrisonResolverBase {
  constructor(protected readonly service: PrisonService) {}

  async _prisonsMeta(
    @graphql.Args() args: PrisonCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Prison])
  async prisons(@graphql.Args() args: PrisonFindManyArgs): Promise<Prison[]> {
    return this.service.prisons(args);
  }

  @graphql.Query(() => Prison, { nullable: true })
  async prison(
    @graphql.Args() args: PrisonFindUniqueArgs
  ): Promise<Prison | null> {
    const result = await this.service.prison(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Prison)
  async deletePrison(
    @graphql.Args() args: DeletePrisonArgs
  ): Promise<Prison | null> {
    try {
      return await this.service.deletePrison(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
