/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Autorisation } from "./Autorisation";
import { AutorisationCountArgs } from "./AutorisationCountArgs";
import { AutorisationFindManyArgs } from "./AutorisationFindManyArgs";
import { AutorisationFindUniqueArgs } from "./AutorisationFindUniqueArgs";
import { DeleteAutorisationArgs } from "./DeleteAutorisationArgs";
import { AutorisationService } from "../autorisation.service";
@graphql.Resolver(() => Autorisation)
export class AutorisationResolverBase {
  constructor(protected readonly service: AutorisationService) {}

  async _autorisationsMeta(
    @graphql.Args() args: AutorisationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Autorisation])
  async autorisations(
    @graphql.Args() args: AutorisationFindManyArgs
  ): Promise<Autorisation[]> {
    return this.service.autorisations(args);
  }

  @graphql.Query(() => Autorisation, { nullable: true })
  async autorisation(
    @graphql.Args() args: AutorisationFindUniqueArgs
  ): Promise<Autorisation | null> {
    const result = await this.service.autorisation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Autorisation)
  async deleteAutorisation(
    @graphql.Args() args: DeleteAutorisationArgs
  ): Promise<Autorisation | null> {
    try {
      return await this.service.deleteAutorisation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
